name: Check
on:
  push:
    branches:
      - main
      - 'develop/**'
  pull_request:
    branches:
      - main
      - 'develop/**'
jobs:
  base:
    uses: ./.github/workflows/base-workflow.yml

  lint:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: Code Linting
        run: npm run lint

      - name: Code Stylelinting
        run: npm run stylelint:fix

  test:
    runs-on: ubuntu-latest
    needs: [base, lint]
    steps:
      - name: Test
        run: npm run test:run
